### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TheLastBilly** [TheLastBilly/psCast#1]
- [x] Add callbacks for extra controls (ie: circle to go back, R to show controls, etc...)
- [x] Add podcast xml parsing 
- [ ] Add database storing for podcasts (Use a text based config file for simplicity)
- [ ] Add download support for tracks
- [ ] Add status bar with battery and time info 
- [ ] Add lower bar for currently playing tracks 
- [ ] Add search bar for downloaded podcasts
- [ ] Add delete on listened option
- [ ] Add max storage used option
- [ ] Add independent index for menu lists
- [ ] Make logo for the project
